### ISSUE TITLE
[Question] How to fill the screens completely?

### ISSUE THREAD

**Issue by joex92** [bitbank2/Multi_OLED#11]
When I used the ssd1306 library I could fill all the screen, but with this library the screens are not filled completely...
Actually when using `Multi_OLEDFill(0, 1)` it only shows 4 lines instead of filling the screen... does this have something to do with a buffer or something like that? how do I manage that? 
With the ssd1306 library I did a clear every loop and it looked seamless, but with `Multi_OLEDFill(0, 0)` you can see the screen being cleared every time, like it can't clear it seamlessly...
hope you understand me...

**Comment by bitbank2** [comment]
Hi Joe,
I'm sorry about issues you're having with this library. I decided a while ago to start from a clean slate and create a library which could manage multiple displays and also support LCDs and specialty displays. This new library is called OneBitDisplay. The Multi_OLED library is deprecated and I didn't plan on making any improvements to it. Give it a try and hopefully you will find it even easier to use and works correctly.

**Comment by joex92** [comment]
Nice! Thanks! But does this new library support multiple i2c displays? that's what I need

**Comment by joex92** [comment]
btw, this is off-topic, but you might have a lot of experience with oled displays...

I'm having an issue, I started with 2 OLED displays of 128x64 pixels, then I just bought a new one... it works, but suddenly the 5V pin started to having some smoke coming out of it, I didn't understand why because the other ones are fine, I even switched the cables and the same thing happened with the same display... 
one thing to notice is that the 2 first ones had the pins in this order: `GND/VCC/SCL/SDA`
but the new one has it like this: `VCC/GND/SCL/SDA`
What might be the problem?
I set them up like this:
```c
uint8_t scl_list[NUM_BUSES] = {3,6,10};
uint8_t sda_list[NUM_BUSES] = {5,9,11};
```

**Comment by bitbank2** [comment]
The new library allows you to support as many simultaneous displays as you want, but in a more C++ class kind of way.
I have OLED displays with all permutations of pin ordering and I once connected the power backwards on one of them. It survived, but got very hot for a few seconds. The pin choices are up to you and depend on the MCU you're using. You can share a single pin for the clock, so your 3 displays only need 4 unique pins to drive them.

**Comment by joex92** [comment]
ok, so it would be like this?
```c
uint8_t scl_list[NUM_BUSES] = {3,3,3};
uint8_t sda_list[NUM_BUSES] = {9,10,11};
```

**Comment by bitbank2** [comment]
yes
