### ISSUE TITLE
Not an issue - Can it work with a mcp23017 gpio expander ?

### ISSUE THREAD

**Issue by tokazio** [bitbank2/Multi_OLED#3]
I need 10 oled screen on an hardware with a small number of pins. Then i added a mcp23017 gpio port expander to drive the oled screens. Is i possible that your lib can drive these screen through the mcp23017 ?

**Comment by bitbank2** [comment]
My code doesn't currently support that; it would take a bit of code to make that work. Why not use an I2C multiplexer like the TCA9548A? I'm sure I could get it working with the MCP23017 (I also have a few on hand), but I you're the first person to ask for it and I don't have need for any of my projects.
