### ISSUE TITLE
How can I use this in ESP8266

### ISSUE THREAD

**Issue by ohminy** [bitbank2/Multi_OLED#6]
It is not a issue.
I think it is very good library and I really want to use this in my ESP8266 project
But I can not know how I can..
I tested all of two examples but both of them are not work..
and I can not understand pin num hex?? like 0xb6.
Can you please teach me how can I use this in ESP8266
(sorry for my english skill..)

**Comment by bitbank2** [comment]
The hex pin numbering is only for ATmega MCUs to speed things up. Use the regular pin numbers on your ESP8266. The library works fine on ESP8266. You need to show me your wiring and code to understand why your project isn't working.

**Comment by ohminy** [comment]
I just solved my problem...
dumbfounded, it was i2c address
my OLED, what I brought from aliexpress, there are silk printed "0x78".
But! the real I2C was "0x3c"......
Finally the library works well !!!
I'm sorry for bothering you.

**Comment by bitbank2** [comment]
My ss_oled library solves that by finding the address automatically (it tests both 0x3c and 0x3d)

**Comment by ohminy** [comment]
If I use your ss_oled library, also can I use multiple OLEDs?
There is no explanation and examples about multi OLEDs in the ss_oled library repository.

**Comment by bitbank2** [comment]
Using multiple OLEDs at once is an "edge case" - few people are interested. SS_OLED is for a single display and has a bunch more features. If you want to pull those features over to the multi-oled library, please do a pull request. Otherwise, I probably won't replicate all of the features.
