### ISSUE TITLE
hello. here to ask abt commands.

### ISSUE THREAD

**Issue by pilotusoo** [bitbank2/Multi_OLED#7]
do you have any manual for commands?
for like.. FONT_SIZE. SMALL,NORMAL,LARGE or HUGE... where can i find that infos.
even large is not that large enough. only use 1/2 or 3/4 of display.

and.. also i have overwriting issue..... :D looking for a command like lcd.clear() something like that... :D

**Comment by bitbank2** [comment]
I detailed everything in the Wiki

https://github.com/bitbank2/OneBitDisplay/wiki

For bigger fonts, you can use a custom font in the Adafruit_GFX format.

**Comment by pilotusoo** [comment]
much more things to study... lol thank you.
