### ISSUE TITLE
line_demo -- Multi_OLEDDrawLine undeclared identifier

### ISSUE THREAD

**Issue by re3me** [bitbank2/Multi_OLED#9]
While attempting to run line_demo - I am greeted with a undeclared identifier on Multi_OLDEDDrawLine 
I have attempted to find the issue but have been unsuccessful.

**Comment by bitbank2** [comment]
Hi re3me,
If you look in the code, you'll see that this function is disabled on AVR targets because they generally don't have enough RAM to hold a backbuffer. You're welcome to change that and enable it (look for Multi_OLEDDrawLine in Multi_OLED.cpp)

**Comment by re3me** [comment]
Hi,
Thank you for the fast response. I may be too stupid or ignorant, but when reviewing the cpp file I don't see how it is disabled.. how do I enable it? I am used to using comments to enable/disable functions.

**Comment by bitbank2** [comment]
The code is blocked off with:
#ifndef AVR
<code here>
#endif

"ifndef" says "if not defined" to compile the code between that and "endif". So in the case of an AVR target, that code will be excluded. Comment out the ifndef and matching endif to enable the code.

**Comment by re3me** [comment]
Ah. Perfect. Thank you for the explanation! It cleared the issue.
